<?xml version="1.0" encoding="UTF-8"?>
<!--***************************************************************************************************************************************************************
Alterations
*******************************************************************************************************************************************************************
Name		| Date			| Change
*******************************************************************************************************************************************************************
J Miguel	| 20/05/2015	| 10269 Brakes Logistics Generic Mapper Clean up
****************************************************************************************************************************************************************-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:sh="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader" xmlns:eanucc="urn:ean.ucc:2" xmlns:order="urn:ean.ucc:order:2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:msxsl="urn:schemas-microsoft-com:xslt" xmlns:vbscript="http://abs-Ltd.com">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:variable name="BPMSR">-MSR</xsl:variable>
	
	<!-- Start point - ensure required outer BatchRoot tag is applied -->
	<xsl:template match="/PurchaseOrder">
		<!-- 2012-04-20 HR 5394 - generate PurchaseOrderTime if not in input XML -->
		<!-- the poTime needs to go in 2 elements. When generated by this script, it should be the same in both elements. (i.e. dont generate 2 different times) -->
		<!-- this variable has been located at the start of the template to ensure it is in scope of both elements that need the time -->
		<xsl:variable name="poTime">
			<xsl:choose>
				<xsl:when test="PurchaseOrderHeader/PurchaseOrderReferences/PurchaseOrderTime != ''">
					<xsl:value-of select="PurchaseOrderHeader/PurchaseOrderReferences/PurchaseOrderTime"/>
				</xsl:when>
				<xsl:otherwise>
					<xsl:value-of select="vbscript:msTime()"/>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:variable>

		<sh:StandardBusinessDocument>
			<sh:StandardBusinessDocumentHeader>
				<!--Fixed value version of Standard Business Header - depends on final format agreed-->
				<sh:HeaderVersion>2.2</sh:HeaderVersion>
				<!--Sender Will be a fixed value probable 'DG Trading'-->
				<sh:Sender>
					<sh:Identifier>
						<xsl:attribute name="Authority">EAN.UCC</xsl:attribute>
						<xsl:value-of select="PurchaseOrderHeader/ShipTo/ShipToName"/>
					</sh:Identifier>
				</sh:Sender>
				<!--Target Vendor  - Description-->
				<sh:Receiver>
					<sh:Identifier>
						<xsl:attribute name="Authority">EAN.UCC</xsl:attribute>
						<xsl:value-of select="PurchaseOrderHeader/Supplier/SuppliersName"/>
					</sh:Identifier>
				</sh:Receiver>
				<sh:DocumentIdentification>
					<sh:Standard>"http://www.w3.org/2001/XMLSchema-instance"</sh:Standard>
					<!--GS1 - Purchase Order version reference - Fixed value-->
					<sh:TypeVersion>2.1</sh:TypeVersion>
					<!--Message Instance identifier set by Vendor-->
					<sh:InstanceIdentifier>1111</sh:InstanceIdentifier>
					<!--Fixed value-->
					<sh:Type>"Purchase Order"</sh:Type>
					<!--date and time Format  YYYY-mm-ddTHH:MM:SS-timezone offset -->
					<!-- 2012-04-10 HR 5394 - add PurchaseOrderTime if not exists -->
					<sh:CreationDateAndTime>
						<xsl:value-of select="concat(PurchaseOrderHeader/PurchaseOrderReferences/PurchaseOrderDate,'T',$poTime)"/>
					</sh:CreationDateAndTime>
				</sh:DocumentIdentification>
			</sh:StandardBusinessDocumentHeader>
			
			<eanucc:message>
			
				<entityIdentification>
					<!--Unique ID for this message - since one message = one Order could be Order number-->
					<uniqueCreatorIdentification>
						<xsl:value-of select="PurchaseOrderHeader/PurchaseOrderReferences/PurchaseOrderReference"/>
					</uniqueCreatorIdentification>
					<contentOwner>
						<!--GLN for DG Trading -->
						<!--Special Case for Brunning and Price Setup, We need to pass GLN based on the Accounting Center of the Ordering Unit-->						
						<gln>	
							<xsl:variable name="GLN"><xsl:value-of select="/PurchaseOrder/PurchaseOrderHeader/Buyer/BuyersLocationID/GLN"/></xsl:variable>	
							<xsl:variable name="Sender"><xsl:value-of select="/PurchaseOrder/PurchaseOrderHeader/ShipTo/ShipToName"/></xsl:variable>						
							<xsl:choose>																										
								<xsl:when test="$GLN = '5060166761233' and $Sender != '' and contains($Sender, $BPMSR)">5060166761257</xsl:when>
								<xsl:when test="$GLN = '5060166761233' and $Sender != '' and not(contains($Sender, $BPMSR))">5060166761233</xsl:when>
								<xsl:otherwise><xsl:value-of select="PurchaseOrderHeader/Buyer/BuyersLocationID/GLN"/></xsl:otherwise>
							</xsl:choose>
						</gln>				
						
						<additionalPartyIdentification>
							<!-- Text Description for DG Trading Eproc-->
							<additionalPartyIdentificationValue>
								<xsl:value-of select="PurchaseOrderHeader/Buyer/BuyersName"/>
							</additionalPartyIdentificationValue>
							<additionalPartyIdentificationType>BUYER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
						</additionalPartyIdentification>
					</contentOwner>
				</entityIdentification>
				
				<!--Start of the Document-->
				<eanucc:documentCommand>
					<!--Type hardcoded to ADD-->
					<documentCommandHeader>
						<xsl:attribute name="type">ADD</xsl:attribute>
						<entityIdentification>
							<!--Unique identifier for Order -->
							<uniqueCreatorIdentification>
								<xsl:value-of select="PurchaseOrderHeader/PurchaseOrderReferences/PurchaseOrderReference"/>
							</uniqueCreatorIdentification>
							<!--DG Trading GLN-->
							<contentOwner>
								<gln>
									<xsl:value-of select="PurchaseOrderHeader/Buyer/BuyersLocationID/GLN"/>
								</gln>
							</contentOwner>
						</entityIdentification>
					</documentCommandHeader>
					<documentCommandOperand>
						<!--Start of Order details - Order Creation date and time. Document Status hardcoded 'ORIGINAL'-->
						<!--Format  YYYY-mm-ddTHH:MM:SS-timezone offset -->
						<order:order>
							<xsl:attribute name="creationDateTime">
								<!-- 2012-04-20 HR 5394 - add PurchaseOrderTime if not exists -->					
								<xsl:value-of select="concat(PurchaseOrderHeader/PurchaseOrderReferences/PurchaseOrderDate,'T',$poTime)"/>
							</xsl:attribute>
							<xsl:attribute name="documentStatus">ORIGINAL</xsl:attribute>
						
							<!--Order details - Unique Purchase Order number-->
							<orderIdentification>
								<uniqueCreatorIdentification>
									<xsl:value-of select="PurchaseOrderHeader/PurchaseOrderReferences/PurchaseOrderReference"/>
								</uniqueCreatorIdentification>
								<contentOwner>
									<gln>
										<xsl:value-of select="PurchaseOrderHeader/Buyer/BuyersLocationID/GLN"/>
									</gln>
								</contentOwner>
							</orderIdentification>
							
							<orderPartyInformation>
								<seller>
									<!--DG Tradings Identification of the Seller -  -->
									<gln>										
										<xsl:value-of select="PurchaseOrderHeader/Supplier/SuppliersLocationID/GLN"/>
									</gln>
									<additionalPartyIdentification>
										<additionalPartyIdentificationValue>
											<xsl:choose>
												<xsl:when test="TradeSimpleHeader/RecipientsBranchReference">
													<xsl:value-of select="TradeSimpleHeader/RecipientsBranchReference"/>
												</xsl:when>
												<xsl:otherwise>
													<xsl:value-of select="PurchaseOrderHeader/Supplier/SuppliersLocationID/BuyersCode"/>
												</xsl:otherwise>
											</xsl:choose>	
											
										</additionalPartyIdentificationValue>
										<additionalPartyIdentificationType>BUYER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
									</additionalPartyIdentification>
								</seller>
								
								<buyer>
									<gln>
										<xsl:value-of select="PurchaseOrderHeader/Buyer/BuyersLocationID/GLN"/>
									</gln>
									<!--Brakes Outlet code -->
									<additionalPartyIdentification>
										<additionalPartyIdentificationValue>
											<xsl:value-of select="PurchaseOrderHeader/ShipTo/ShipToLocationID/SuppliersCode"/>
										</additionalPartyIdentificationValue>
										<additionalPartyIdentificationType>SELLER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
									</additionalPartyIdentification>
								</buyer>
							</orderPartyInformation>
							
							<orderLogisticalInformation>
								<shipToLogistics>
									<shipTo>
										<gln>
											
											<!-- specific default GLN requirement for Logistics (5036036000030) -->
											<xsl:choose>
												<xsl:when test="PurchaseOrderHeader/ShipTo/ShipToLocationID/GLN='5555555555555' and PurchaseOrderHeader/Supplier/SuppliersLocationID/GLN='5036036000030'">
													<xsl:text>0000000000000</xsl:text>
												</xsl:when>												
												<xsl:otherwise>
													<xsl:value-of select="PurchaseOrderHeader/ShipTo/ShipToLocationID/GLN"/>
												</xsl:otherwise>												
											</xsl:choose>			
																			
										</gln>
										<!--DG Trading Outlet code -->
										<additionalPartyIdentification>
											<additionalPartyIdentificationValue>
												<xsl:value-of select="PurchaseOrderHeader/ShipTo/ShipToLocationID/BuyersCode"/>
											</additionalPartyIdentificationValue>
											<additionalPartyIdentificationType>BUYER_ASSIGNED_IDENTIFIER_FOR_A_PARTY</additionalPartyIdentificationType>
										</additionalPartyIdentification>
									</shipTo>
								</shipToLogistics>
								<orderLogisticalDateGroup>
									<requestedDeliveryDate>
										<date>
											<xsl:value-of select="PurchaseOrderHeader/OrderedDeliveryDetails/DeliveryDate"/>
										</date>
										<time>
											<xsl:choose>
												<xsl:when test="string(PurchaseOrderHeader/OrderedDeliveryDetails/DeliverySlot/SlotStart) != ''">
													<xsl:value-of select="PurchaseOrderHeader/OrderedDeliveryDetails/DeliverySlot/SlotStart"/>
												</xsl:when>
												<xsl:otherwise>00:00:00</xsl:otherwise>
											</xsl:choose>										
										</time>
									</requestedDeliveryDate>
								</orderLogisticalDateGroup>
							</orderLogisticalInformation>
							
							<tradeAgreement>
								<!-- DG Trading Price Level -->
								<tradeAgreementReferenceNumber>
									<xsl:choose>
										<xsl:when test="PurchaseOrderHeader/PurchaseOrderReferences/TradeAgreement/ContractReference">
											<xsl:value-of select="PurchaseOrderHeader/PurchaseOrderReferences/TradeAgreement/ContractReference"/>
										</xsl:when>
										<xsl:otherwise>1</xsl:otherwise>
									</xsl:choose>
								</tradeAgreementReferenceNumber>
							</tradeAgreement>
							
							<xsl:for-each select="PurchaseOrderDetail/PurchaseOrderLine">								
								
								<orderLineItem>
								
									<xsl:attribute name="number">
										<xsl:value-of select="count(preceding-sibling::* | self::*)"/>
									</xsl:attribute>
								
									<requestedQuantity>
									
										<value>
											<xsl:choose>
												<xsl:when test=".='KG'">
													<xsl:value-of select="format-number(OrderedQuantity,'0.000')"/>
												</xsl:when>
												<xsl:otherwise>
													<xsl:value-of select="format-number(OrderedQuantity,'#0')"/>
												</xsl:otherwise>
											</xsl:choose>											
										</value>
										
										<unitOfMeasure>
											<measurementUnitCodeValue>
												<xsl:choose>
													<!--MacDonald Hotels-->
													<xsl:when test="/PurchaseOrder/PurchaseOrderHeader/Buyer/BuyersLocationID/GLN = 5060166760021">
														<xsl:text>EA</xsl:text>
													</xsl:when>
													<!--Mercure-->
													<xsl:when test="/PurchaseOrder/PurchaseOrderHeader/Buyer/BuyersLocationID/GLN = 5027615900020">
														<xsl:text>EA</xsl:text>
													</xsl:when>
													<xsl:otherwise>
														<xsl:value-of select="OrderedQuantity/@UnitOfMeasure"/>
													</xsl:otherwise>
												</xsl:choose>
											</measurementUnitCodeValue>
										</unitOfMeasure>
										
									</requestedQuantity>
									
									<tradeItemIdentification>
									
										<gtin>
											<xsl:value-of select="ProductID/GTIN"/>
										</gtin>
										
										<additionalTradeItemIdentification>
											<!-- Suppliers material code -->
											<additionalTradeItemIdentificationValue>
												<xsl:value-of select="ProductID/SuppliersProductCode"/>
											</additionalTradeItemIdentificationValue>
											<additionalTradeItemIdentificationType>SUPPLIER_ASSIGNED</additionalTradeItemIdentificationType>
										</additionalTradeItemIdentification>
										
										<additionalTradeItemIdentification>
											<!-- Text Description of Material -->
											<additionalTradeItemIdentificationValue>
												<xsl:value-of select="substring(ProductDescription,1,35)"/>
											</additionalTradeItemIdentificationValue>
											<additionalTradeItemIdentificationType>BUYER_ASSIGNED</additionalTradeItemIdentificationType>
										</additionalTradeItemIdentification>
										
									</tradeItemIdentification>
									
								</orderLineItem>
								
							</xsl:for-each>
								
						</order:order>
						
					</documentCommandOperand>
					
				</eanucc:documentCommand>
				
			</eanucc:message>
			
		</sh:StandardBusinessDocument>

	</xsl:template>

<!-- output time -->
<msxsl:script language="VBScript" implements-prefix="vbscript"><![CDATA[ 

Function msTime

msTime= CStr(TimeValue(Now))

End Function
]]></msxsl:script>

</xsl:stylesheet>
